In [2]:
import sys
sys.path.insert(1, '..')
from main_code.utils.config.config import Config
from main_code.tester.tsp_tester import TSPTester

class LampenergyForecastingConfig(Config):

    def __init__(self, config_yaml=None) -> None:

        # forecasting performer sub config

        self.performer_config = Config()

        self.performer_config.set_defaults(TSPTester)



In [3]:
trest = LampenergyForecastingConfig()
trest.to_df()

performer_config
num_trajectories                1
num_nodes                      20
num_samples               10000.0
sampling_steps                  1
use_pomo_aug                False
test_set_path                None
test_batch_size              1024

In [38]:
import numpy as np
result = []
for i in range(2):
    x = np.random.rand(3,2)
    y = np.random.rand(5,)
    z = np.random.randn()

    test = (x,y,z)
    result.append(test)
result    


[(array([[0.27911984, 0.47287709],
         [0.81496336, 0.70076588],
         [0.45440156, 0.15589319]]),
  array([0.31485648, 0.36485509, 0.57756984, 0.78475044, 0.26351264]),
  0.5935635941130768),
 (array([[0.06172984, 0.59147676],
         [0.168262  , 0.32263822],
         [0.94579896, 0.70738247]]),
  array([0.54323135, 0.39979627, 0.58416065, 0.83135756, 0.01578773]),
  -0.3864225551680165)]

In [46]:

tmp_arr = np.array(result, dtype=object)
batch_s = tmp_arr.shape[0]
node_feats = np.concatenate(tmp_arr[:,0]).reshape(batch_s,-1, 2)
opt_tour = np.concatenate(tmp_arr[:,1]).reshape(batch_s,-1).astype(np.int8)
opt_tour_len = tmp_arr[:,2].astype(np.float64)

In [47]:
opt_tour

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [31]:
arr = np.array(result, dtype=object)[:,1]
arr.astype(np.float64)

array([2., 2.])

In [3]:
class test:
    def __init__(self, popo) -> None:
        self.popo = popo

popo = [1,2,34,5,6,7]
test1 = test(popo)
test1.popo.pop(0)
print(popo)

[2, 34, 5, 6, 7]
